---
title: "Brownie citron"
---

## 🛒 Ingrédients
Pour 16 parts
 
Brownie au citron

- 200g de sucre
- 110g de beurre
- 1 citron
- 125g de chocolat blanc
- 2 œufs
- 2 c à c d'extrait de vanille
- 160g de farine
- 1/4 de c à c de sel
 
Glaçage au citron

- 125g de sucre en poudre
- 2/3 c à s de jus de citron

## 🔪 Ustensiles
- Moule à gâteau de 20x20cm
- Bol à mélanger
- Fouet
- Marise

## 🔢 Étapes
Brownie au citron

1. Préchauffer le four à 160°C (four conventionnel). Préparer un moule carré de 20x20 cm avec du papier sulfurisé. 
2. Faire fondre le beurre et l'ajouter dans un petit bol. Ajouter les pépites de chocolat et mélanger jusqu'à ce qu'elles soient fondues. Mettre de côté.
3. Dans un autre grand bol, ajouter le sucre cristallisé et le zeste de citron. Frotter le tout pour libérer tout l'arôme de citron jusqu'à ce que le mélange ressemble à du sable mouillé. Ajouter le beurre fondu/le chocolat blanc au sucre et, à l'aide d'un fouet à main, mélanger le tout jusqu'à obtention d'une pâte homogène. Il se peut que le mélange ait l'air un peu fendu, mais ne vous inquiétez pas.
4. Ajouter les œufs et mélanger jusqu'à ce qu'ils soient incorporés. Une fois incorporés, continuez à bien les fouetter pendant 1 à 2 minutes pour qu'ils deviennent légers et mousseux.
5. Ajoutez ensuite le jus de citron et l'extrait de vanille et fouettez jusqu'à ce qu'ils soient combinés.
6. Ajouter les ingrédients secs à la pâte et fouetter délicatement jusqu'à ce qu'ils soient combinés.
7. Ajoutez la pâte à brownie dans le moule préparé et lissez-la à l'aide d'une spatule.
8. Faire cuire au four pendant 30 à 32 minutes. Le brownie restera léger et ne brunira pas. Une fois cuit, laissez-le refroidir complètement sur une grille.
9. Une fois complètement refroidi, le retirer du moule et le placer dans un plat de service pour préparer le glaçage au citron.

Glaçage au citron

1. Dans un petit bol, ajouter le sucre en poudre et commencer par 2 cuillères à soupe de jus de citron. Mélanger jusqu'à obtention d'un mélange homogène. Ajouter plus de jus de citron si nécessaire ou jusqu'à ce que le mélange soit lisse.
2. Ajouter le glaçage au citron sur le brownie et l'étaler. Décorez éventuellement avec du zeste de citron. Laisser prendre à température ambiante. Vous pouvez également le placer au réfrigérateur pour qu'il prenne plus rapidement. Une fois que le glaçage a pris et s'est raffermi, il est prêt à être servi.

