---
title: "Cake citron"
---

## 🛒 Ingrédients
- 200g de sucre blanc
- 2 citrons
- 3 œufs
- 10cL de crème liquide
- 1 c à c de levure chimique
- 190g de farine
- 70g de beurre fondu
- 2 c à soupe de graines de pavot
- 250g de sucre glace

## 🔪 Ustensiles
- Bol à mélanger
- Moule à cake de 25cm

## 🔢 Étapes
1. Mélanger les 200g de sucre blanc avec le zest des deux citrons.
2. Ajouter les 3 œufs et mélanger (mélange blanchi).
3. Ajouter les 10cL de crème liquide et le jus d'un citron puis mélanger.
4. Ajouter une c à c de levure chimique et mélanger.
5. Incorporer les 190g de farine en plusieurs fois.
6. Ajouter les 70g de beurre fondu refroidi et mélanger.
7. Ajouter les 2 c à soupe de graines de pavot.
8. Verser le mélange dans le moule à cake et faire cuire pendant 1h à 160°C.
9. Faire refroidir le cake avant de mettre le glaçage.
10. Pour le glaçage, mélanger les 250g de sucre glace avec le jus d'un citron. Verser progressivement le jus jusqu'à avoir un mélange liquide mais pas trop coulant (pour qu'il reste sur le cake). Verser le glaçage sur le cake et faire refroidir le cake.
