---
title: "Carrot cake"
---

## 🛒 Ingrédients

Pour 8 personnes (un moule à cake)

- 90g d'huile végétale
- 125g de sucre
- 125g de farine fluide
- 150g de carotte râpées (2 grosses carottes)
- 2 œufs
- 1 c à c d'extrait de vanille
- 1/2 c à c rase de muscade
- 1 c à c rase de cannelle
- 1/2 sachet de levure chimique

## 🔪 Ustensiles

- Bol à mélanger
- Râpe à légume
- Moule à cake

## 🔢 Étapes

1. Mélanger au fouet les 2 œufs et le sucre.
2. Incorporer l'extrait de vanille, la muscade, la cannelle et l'huile, mélanger avec le fouet.
3. Ajouter la farine et la levure, mélanger jusqu'à obtenir une pâte lisse.
4. Ajouter les carottes râpées, mélanger jusqu'à obtenir une pâte homogène.
5. Éventuellement huiler et fariner le moule puis verser la préparation.
6. Enfourner 30 à 40 minutes (plutôt 40 min pour éviter que le gâteau ne colle trop) selon le four à 175°C. Piquer pour vérifier que le gâteau soit cuit.
7. Optionnel : ajouter un glaçage avec du sucre glace et de l'eau.

Source : [Marmiton - Carrot Cake : la vraie recette](https://www.marmiton.org/recettes/recette_veritable-carrot-cake-recette-usa_83584.aspx)