---
title: "Cookies"
---

## 🛒 Ingrédients

Pour 6 personnes / 16 cookies

- 1 œuf
- 85g de sucre
- 85g de beurre doux
- 150g de farine
- 100g de pépites de chocolat ou de tablette de chocolat
- 1 sachet de sucre vanillé
- 1 c à c de levure chimique
- 1/2 c à c de sel

## 🔪 Ustensiles

- Bol à mélanger
- Plaque de cuisson

## 🔢 Étapes

1. Laisser ramollir le beurre à température ambiante. Dans un saladier, malaxer le avec le sucre.
2. Ajouter l'œuf et éventuellement le sucre vanillé.
3. Verser progressivement la farine, la levure chimique, le sel et les pépites de chocolat. Mélanger bien.
4. Beurrer une plaque allant au four ou la recouvrir d'une plaque de silicone. À l'aide de deux cuillères à soupe ou simplement avec les mains, former des noix de pâte en les espaçant car elles s'étaleront à la cuisson.
5. Faire cuire 8 à 10 minutes à 180°C (thermostat 6). Il faut les sortir dès que les contours commencent à brunir.

Source : Le journal des femmes https://cuisine.journaldesfemmes.fr/recette/310548-american-cookies
