---
title: "Crumble aux pommes"
---

## 🛒 Ingrédients

 Pour 8 personnes

- 150g de farine
- 150g de sucre (ou 100g de sucre et 50g de cassonade)
- 150g de beurre (demi-sel ?)
- 8 spéculoos
- 6 pommes (ou 4 pommes et 2 poires)
- 1 sachet de sucre vanillé
- 2 c à s de sucre
- 1/2 verre d'eau

## 🔪 Ustensiles

- Bol à mélanger
- Casserole
- Plat à gâteau rectangulaire

## 🔢 Étapes

1. Éplucher les pommes (et les poires) et les couper en dés (grossièrement).
2. Faire mijoter pendant 10 minutes (en tournant de temps en temps) les fruits coupés avec 1/2 verre d'eau, un sachet de sucre vanillé et 2 c à s de sucre.
3. Préchauffer le four 10 minutes à 210°C.
4. Mélanger 150g de farine avec 150g de sucre (ou 100g de sucre et 50g de cassonade).
5. Ajouter les spéculoos émiettés et mélanger le tout.
6. Ajouter 150g de beurre coupé en dés. Le beurre doit être pommade pour être plus facilement travaillé.
7. Malaxer le tout qui doit rester hétérogène. Prendre garde à ce que la préparation ne devienne pas une pâte sablée.
8. Mettre les fruits au fond du plat en prenant soin d'enlever l'excédent d'eau.
9. Émietter la pâte sur les fruits.
10. Mettre au four 20 minutes.

Source : [Marmiton - Crumble aux pommes poire et spéculoos](https://www.marmiton.org/recettes/recette_crumble-aux-pommes-poire-et-speculoos_166011.aspx)