---
title: "Flan patissier"
---

## 🛒 Ingrédients

- 1 pâte feuilletée
- 100g de poudre à flan pâtissier (impérial)
- 1L de lait
- 2 jaunes d'œuf
- 130 de sucre

## 🔪 Ustensiles

- Bol à mélanger
- Casserole
- Fouet
- Marise

## 🔢 Étapes

1. Etaler la pâte feuilletée dans un mouler et faire des trous avec une fourchette.
2. Prendre deux saladiers. Dans le premier, mélanger 1/2L de lait avec le sucre et faire chauffer le mélange dans une casserole jusqu’à ébullition.
3. Dans le second saladier, mélanger la poudre à flan pâtissier avec 1/2L de lait. Ensuite, rajouter les deux jaunes d’œuf.
4. Une fois le premier mélange arrivé à ébullition, couper le feu (enlever la casserole du feu) et incorporer doucement le second mélange en plusieurs fois tout en battant (et bien dans les coins pour éviter que cela ne brule).
5. Remettre sur feu doux et continuer de mélanger avec le fouet jusqu’à épaississement (1-2min après épaississement).
6. Verser le mélange dans le moule et laisser reposer 30min-1h pour faire « crouter » le dessus (et éviter que le flan n’explose à la cuisson).
7. Faire cuire le flan 30min à 180°C sans ouvrir le four et continuer à cuire jusqu’à ce que le dessus ait une bonne couleur.
