---
title: "Galette des rois"
---

## 🛒 Ingrédients

- 2 disques de pâte feuilletée pur beurre
- 125g de beurre
- 125g de sucre
- 2 œufs
- 125g de poudre d'amande
- 1 c à s de compote de pomme
- 1 fève (facultatif)
- dorure : 1 jaune d'œuf et 1 c à c de lait

## 🔪 Ustensiles

- Bol à mélanger
- Pinceau
- Plaque de cuisson

## 🔢 Étapes

1. Mélanger le beurre ramolli avec le sucre.
2. Ajouter les œufs puis la poudre d'amande et la compote.
3. Étaler le premier disque de pâte feuilleter et déposer la garniture sur la pâte en laissant 2cm de pâte vide sur le bord.
4. Ajouter la fève et mouiller le bord avec un pinceau.
5. Recouvrer avec le deuxième disque de pâte feuilletée.
6. Appuyer sur les bords pour les souder.
7. Mettre une première couche de dorure avec un pinceau et placer la galette au frais pour 30 min.
8. Préchauffer le four à 200°C (Th 6/7).
9. Sortir la galette et étaler une deuxième couche de dorure au pinceau.
10. Faire un décor avec le couteau et faire des petits trous.
11. Faire cuire 20 à 30 minutes.
