---
title: "Quiche lorraine"
---

## 🛒 Ingrédients

- 1 pâte feuillée ou brisée
- 200g de lardons fumés
- 3 œufs
- 100mL de lait
- 200-300g de crème fraiche épaisse entière

## 🔪 Ustensiles

- Plat à tarte
- Bol à mélanger

## 🔢 Étapes

1. Préchauffer le four à 180°C
2. Appliquer la pâte feuilletée dans le moule (en gardant le papier sulfu présent dans l’emballage) et enlever les bords qui dépassent. Faire des trous avec une fourchette (fond voire également sur les côtés) pour éviter que la pâte gonfle
3. Rajouter les lardons sur la pâte feuilletée (possible de les faire légèrement cuire avant)
4. Préparation de l’appareil œuf-lait-crème.
5. Casser trois œufs et les mélanger avec sel + poivre (pas trop de sel car les lardons sont déjà salés)
6. Incorporer la crème et mélanger
7. Rajouter un peu de lait et mélanger
8. Une fois le four chaud (pour ne pas détremper la pâte feuilletée/brisée avec l’appareil), verser l’appareil dans le moule et enfourner pendant 30 min. Rajouter le temps nécessaire pour obtenir une bonne couleur générale de la quiche
