---
title: "Quiche brocolis poulet tomate"
---

## 🛒 Ingrédients

- 1 pâte feuilletée ou brisée
- 2 bouquets de brocolis (1/2 paquet de brocolis surgelés)
- 2 blancs de poulets cuits
- 3 petites tomates
- 100cL de lait
- 3 œufs
- moutarde

## 🔪 Ustensiles

- Bol à mélanger
- Plat à tarte

## 🔢 Étapes

1. Préchauffer le four à 180°C
2. Appliquer la pâte feuilletée dans le moule (en gardant le papier sulfurisé présent dans l’emballage) et enlever les bords qui dépassent. Faire des trous avec une fourchette (fond voire également sur les côtés) pour éviter que la pâte gonfle
3. Faire cuire les brocolis.
4. Badigeonner le fond de la pâte avec de la moutarde.
5. Couper les tomates en rondelles et les placer au fond de la tarte.
6. Disposer les brocolis et les morceaux de poulet.
7. Préparation de l’appareil œuf-lait-crème.
8. Casser trois œufs et les mélanger avec sel + poivre.
9. Incorporer la crème et mélanger
10. Rajouter un peu de lait et mélanger
11. Une fois le four chaud (pour ne pas détremper la pâte feuilletée/brisée avec l’appareil), verser l’appareil dans le moule et enfourner pendant 30 min. Rajouter le temps nécessaire pour obtenir une bonne couleur générale de la quiche

